### ISSUE TITLE
Your Task is completely ready. You can draw with three colors on Image and also erase and save image. so dm me to proceed

### ISSUE THREAD

**Issue by Muhammad-Awais-Awan** [jaegeun1393/Fiverr_Request#1]
Kindly msg me on upwork or create a separate branch here so I  push the code on that branch and create a pull request.
Thank you.
Muhammad Awais

**Comment by syauqiahmd** [comment]
Hi, i saw your post on upwork looking for the drawing on the image feature by using reactJS. I already done a sample project like what you looking for. May be i can help you with discount cause its my first gigs on upwork, and i need a client.

Thanks

**Comment by Muhammad-Awais-Awan** [comment]
![IMG-20230713-WA0016](https://github.com/jaegeun1393/Fiverr_Request/assets/77565559/bb2feeb6-c320-4915-9acb-3158c93908d6)
